### ISSUE TITLE
Call to undefined method Yega\Auth\JWTGuard::handle()

### ISSUE THREAD

**Issue by Elhebert** [gboyegadada/lumen-jwt#5]
Hi,

I followed the steps detailed in the README, unfortunately, I'm having issue when Lumen is going through the middleware.

I'm having a `Call to undefined method Yega\Auth\JWTGuard::handle()`, And I can't find anything that would explain this.

The routes that have the `auth:api` middleware are all failing and returns the error message.

The login process, and token generation is working properly.

Any idea ?

Here's the whole trace:

```
[2017-06-20 05:32:46] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Yega\Auth\JWTGuard::handle() in /var/www/vendor/illuminate/auth/AuthManager.php:294
Stack trace:
#0 /var/www/vendor/illuminate/pipeline/Pipeline.php(148): Illuminate\Auth\AuthManager->__call('handle', Array)
#1 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#2 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#3 /var/www/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#4 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#6 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#7 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/vendor/palanik/lumen-cors/LumenCors.php(105): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/vendor/illuminate/pipeline/Pipeline.php(148): palanik\lumen\Middleware\LumenCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#17 /var/www/public/index.php(28): Laravel\Lumen\Application->run()
#18 {main}  
```

**Comment by gboyegadada** [comment]
Hi @Elhebert, I found a similar issue [here](https://stackoverflow.com/questions/42428191/middleware-call-to-undefined-method-illuminate-auth-requestguardhandle). Please read through answers. 

Have you added these to your `.env` file? (and put in your own values e.g. the jwt key and issuer). 

````
# required fields
JWT_KEY=XXXXXXXXXXXXXXXXXXXXX
JWT_EXPIRE_AFTER=7200
JWT_ISSUER=myappname-or-domain

# optional fields
JWT_INCLUDE=id,email,avatar,full_name,first_name,last_name
JWT_NBF_DELAY=5
````

JWT_INCLUDE should also contain fields you actually have in your `users` db table (remove the ones that don't exist)
